config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do

      resources :users do
        resources :transactions
        resources :stocks
      end

      resources :companies do
        resources :stocks
      end
      
    end
  end

  get 'sessions/new'
 
  get 'welcome/index'

  resources :sessions

  get 'signup', to: 'users#new', as: 'signup'
get 'login', to: 'sessions#new', as: 'login'
get 'logout', to: 'sessions#destroy', as: 'logout'
get 'stocks/update_stocks_available'
get 'transactions/view_user_transaction'
get 'transactions/companywise_stocks_bought'
get 'transactions/stockwise_total_transaction'
get 'transactions/total_purchase_sale'
get 'transactions/sell_stock'
get 'transactions/update_number_of_stock'
get 'stocks/user_specific_stocks'


  resources :users do
    resources :transactions
    resources :stocks
  end

  resources :companies do
  	resources :stocks
  end

  resources :stocks
  resources :transactions

  #root 'welcome#index'
  root 'sessions#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
has_secure_password

has_many :transactions, dependent: :destroy
has_many :stocks, through: :transactions

validates :name, presence: true, length: {minimum: 5}

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApiController
  
  before_action :set_id,only: :show

  def index
  	render json: User.all
  end

  def show
  end

  private
    def set_id
    	@user = User.find(params[:id])
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :require_login, only: [:new, :create]
  # before_action :already_login

  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def create
  	@user = User.new(users_params)
    
    if @user.save
      log_in(@user)
      redirect_to welcome_index_path,notice: "thank you!"
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(users_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end
  
  private
    def users_params
    	params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="container">
  <div id="signup">
    <div id="signup_header">
      <h1>Sign Up</h1>
    </div>
    <div id="signup_block">
      <%= form_for @user do |form| %>

        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@user.errors.count, "error")%> prohibited this user from being saved:
            </h2>
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>     


        <p>
          <%= form.label :Name %>
          <%= form.text_field :name %>
        </p>
          <p>
          <%= form.label :Email %>
          <%= form.text_field :email %>
        </p>
          <p>
          <%= form.label :Password %>
          <%= form.password_field :password %>
        </p>
            <p>
          <%= form.label :Password_confirmation %>
          <%= form.password_field :password_confirmation %>
        </p>
        <p>
          <%= form.submit %>
        </p>
      <% end %>  
    </div>
   </div> 
</div>    

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

<% if current_user==17 %>
  <%= link_to 'Back', users_path %>
<% else %>
  <%= link_to 'Home', welcome_index_path %>
<% end %>    

app/views/users/index.html.erb
<h1>Listing Users</h1>
<table>
	<tr>
		<th>Name</th>
	</tr>
	<% @users.each do |user| %>
	  <tr>
	  	<td><%= user.name %></td>
	  	<td><%= link_to 'Show', user_path(user) %></td>
	  	<td><%= link_to 'Edit', edit_user_path(user) %></td>
	  	<td><%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: 'Are you sure'} %></td>
	  	<td><%#= link_to 'List All Stocks Bought', transactions_path(@transaction,u_id: user) %></td>
	  </tr>	
    <% end %>
</table>	

<%= link_to 'Create New User', new_user_path %>
<%= link_to 'View Companies', companies_path %>

app/views/users/new.html.erb
<!-- <h1>New User</h1> -->

<%= render 'form' %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
<strong>Email:</strong>
  <%= @user.email %>
</p>  

<%= link_to 'Edit', edit_user_path(@user) %>
<% if current_user==17 %>
  <%= link_to 'Back', users_path %>
<% else %>
  <%= link_to 'Home', welcome_index_path %>
<% end %>    