config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do

      resources :users do
        resources :transactions
        resources :stocks
      end

      resources :companies do
        resources :stocks
      end
      
    end
  end

  get 'sessions/new'
 
  get 'welcome/index'

  resources :sessions

  get 'signup', to: 'users#new', as: 'signup'
get 'login', to: 'sessions#new', as: 'login'
get 'logout', to: 'sessions#destroy', as: 'logout'
get 'stocks/update_stocks_available'
get 'transactions/view_user_transaction'
get 'transactions/companywise_stocks_bought'
get 'transactions/stockwise_total_transaction'
get 'transactions/total_purchase_sale'
get 'transactions/sell_stock'
get 'transactions/update_number_of_stock'
get 'stocks/user_specific_stocks'


  resources :users do
    resources :transactions
    resources :stocks
  end

  resources :companies do
  	resources :stocks
  end

  resources :stocks
  resources :transactions

  #root 'welcome#index'
  root 'sessions#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord

has_many :stocks, dependent: :destroy

validates :name, presence: true, length: { minimum: 5}

end

app/controllers/api/v1/companies_controller.rb
class Api::V1::CompaniesController < ApiController
  before_action :set_id, only: :show

  def index
  	render json: Company.all
  end

  def show
  	render json: @company
  end

  private
  
    def set_id
    	@company = Company.find(params[:id])
    end
    
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_action :authorize
  
  def index
  	@companies = Company.all
  end

  def show
  	@company = Company.find(params[:id])
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def new
    @r = Company.pluck(:name, :id)
    @company = Company.new
  end

  def edit
    @company = Company.find(params[:id])
  end

  def create
  	@company = Company.new(company_params)
  	if @company.save
  	  redirect_to companies_path
    else
      render 'new'
    end
  end

  def update
    @company = Company.find(params[:id])

    if @company.update(company_params)
      redirect_to @company
    else
      render 'edit'
    end
  end

  def destroy
  	@company = Company.find(params[:id])
  	@company.destroy

  	redirect_to companies_path
  end

  private 
    def company_params
    	params.require(:company).permit(:name,:unique_id)
    end


end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<div class="container company-form">
  <%= form_with model: @company, local: true do |form| %>
    <% if @company.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@company.errors.count, "error")%> prohibited this company from being saved:
        </h2>
        <ul>
          <% @company.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= form.label :Company_Name %>
      <%= form.text_field :name %>
    </p>
    <p>
      <%= form.label :Unique_Id %>
      <%= form.text_field :unique_id %>
    </p>
    <p id="action">
      <%= form.submit %>
    </p>

  <% end %> 
</div>  

app/views/companies/edit.html.erb
<div class="container company-edit">
  <h1>Edit Company</h1>

  <%= render 'form' %>  

	<div class="back-button">
	  <%= link_to 'Back', companies_path, class: 'btn btn-secondary btn-lg active' %>
	</div>
</div>

app/views/companies/index.html.erb
<div class="container company-index">
  <div class="pull-left">   
	<h1>Listing Companies</h1>
  </div>
  <div class="pull-right">
    <% if current_user.id==17 %>
	  <%= link_to 'Add New Company', new_company_path, class: "btn btn-primary" %>
	  <%= link_to 'View Users', users_path, class: "btn btn-primary" %>
	<% end %>  
  </div>	  	
	<table>
		<tr>
			<th>Name</th>
			<th>Unique Id</th>
		</tr>
		<div id="company_list">
			<% @companies.each do |company| %>
			  <tr>
			  	<td id="td"><%= company.name %></td>
			  	<td id="td"><%= company.unique_id %></td>
			  	<td><%= link_to 'Show', company_path(company), class:"link-to" %></td>
			  	<% if current_user.id==17 %>
			  	  <td><%= link_to 'Edit', edit_company_path(company), class:"link-to" %></td>
			  	  <td><%= link_to 'Destroy', company_path(company), method: :delete, data: { confirm: 'Are you Sure?'}, class:"link-to" %></td>
			  	<% end %>  
			  </tr>
			<% end %>  
		</div>	
	</table>	
</div	

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>       

app/views/companies/show.html.erb
<div class="container company-show">
  <div>
    <div class="pull-left">
      <h1 id="listing_stock_header">Listing Stocks</h1>
    </div>
    <div class="pull-right">
      <% if current_user.id==17 %>
        <%= link_to 'Create Stock', new_company_stock_path(@company), class: 'btn btn-primary' %>
      <% end %> 
    </div>   
  </div>
  <div>
    <table>
    	<tr>
    		<th>Name</th>
    		<th>Total Stocks</th>
    		<th>Stocks Available</th>
    		<th>Price</th>
    	</tr>
      <div>
      	<% @company.stocks.each do |stock| %>
        	  <tr>
        	  	<td id="td"><%= stock.name %></td>
        	  	<td id="td"><%= stock.total_stocks %></td>
        	  	<td id="td"><%= stock.stocks_available %></td>
        	  	<td id="td"><%= stock.price %></td>
              <% if current_user.id==17 %>
                <td><%= link_to 'Edit', edit_stock_path(stock), class: 'link-to' %></td> 
        	  	  <td><%= link_to_if stock.total_stocks==stock.stocks_available, 'Delete', stock_path(stock,comp_id: @company) , method: :delete, data: { confirm: 'Are You Sure?' }, class: 'link-to' %></td>
              <% else %>            
                <% if stock.stocks_available>=1 %>
          	  	  <td><%= link_to 'Buy Stock', new_user_transaction_path( user_id: @current_user.id, stock_id: stock.id), class: 'link-to' %></td>
                <% else %>
                  <td id="td"><p><i>Stocks Not Available</i></p></td>
                <% end %>    
              <% end %>  
        	  </tr>
        <% end %>  
      </div>  
    </table>
  </div>  

<div class="back-button">
  <%= link_to 'Back', companies_path, class: 'btn btn-secondary btn-lg active' %>
</div>


 <!-- /[stock.company, stock]/ -->