config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do

      resources :users do
        resources :transactions
        resources :stocks
      end

      resources :companies do
        resources :stocks
      end
      
    end
  end

  get 'sessions/new'
 
  get 'welcome/index'

  resources :sessions

  get 'signup', to: 'users#new', as: 'signup'
get 'login', to: 'sessions#new', as: 'login'
get 'logout', to: 'sessions#destroy', as: 'logout'
get 'stocks/update_stocks_available'
get 'transactions/view_user_transaction'
get 'transactions/companywise_stocks_bought'
get 'transactions/stockwise_total_transaction'
get 'transactions/total_purchase_sale'
get 'transactions/sell_stock'
get 'transactions/update_number_of_stock'
get 'stocks/user_specific_stocks'


  resources :users do
    resources :transactions
    resources :stocks
  end

  resources :companies do
  	resources :stocks
  end

  resources :stocks
  resources :transactions

  #root 'welcome#index'
  root 'sessions#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController


  def index
    @transactions = Transaction.all
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def new
  	#@company_id = params[:compa_id]
    @user_id = params[:user_id]
    @stock_id = params[:stock_id]
    @stock = Stock.find(params[:stock_id])
    @stav = @stock.stocks_available
    @company_id = Stock.find_by_id(@stock_id).company.id
    @transaction = Transaction.new
  end

  def edit
    @transaction = Transaction.find(params[:id])
  end

  def create
    /binding.pry/
    @transaction = Transaction.new(transactions_params)
    if @transaction.save

       @price = Stock.find(@transaction.stock_id).price 
       @tcost = @transaction.stocks_bought*@price
       @transaction.total_cost = @tcost
       @transaction.save 

      redirect_to stocks_update_stocks_available_path(t_id: @transaction.id)
    else
      redirect_to transactions_path,flash: {success: "not created!!"}
    end
  end

  def update
    @transaction = Transaction.find(params[:id])
    @stock = Stock.find(@transaction.stock_id)
    if @transaction.update(transactions_params)
      @transaction.stocks_sold_count += @transaction.stocks_sold
      @transaction.sold_total += @transaction.stocks_sold*@stock.price
      @transaction.save
      @stock.stocks_available = @stock.stocks_available+@transaction.stocks_sold
      @stock.save
      redirect_to transactions_path, flash: {success: "Stock Sold!!" }
    else
      render 'edit'
    end
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    redirect_to transactions_path
  end

  def view_user_transaction
  end

  def companywise_stocks_bought
    
  end

  def stockwise_total_transaction
    @st = Stock.find(params[:s])
  end

  def total_purchase_sale
  end

  def sell_stock
    @transaction = Transaction.find(params[:t_id])
  end

  def update_number_of_stock
    @transaction = Transaction.find(params[:t_id])
  end

  private
    def transactions_params
      params.require(:transaction).permit(:stocks_bought, :total_cost, :comp_id, :stock_id, :user_id, :Purchasetotal,:stocks_sold)
    end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/companywise_stocks_bought.html.erb
<h1>companywise_stocks_bought</h1>
<h2><i>Stock Bought Of the Listed Companies</i></h2>



<table>
  <tr>
    <th>Company Name</th>
    <th>Amount Invested</th>
    <th>Amount Of Stocks Sold</th>
    <th>Amount Reedemed</th>
  </tr>
  <% current_user.transactions.select(:comp_id).distinct.each do |thing| %>
  <tr>
  	<% @tpur=0 %>
    <% @tsold=0 %>
  	<% @cid = thing.comp_id %>
  	<% current_user.transactions.each do |i| %>
      <% if i.comp_id==@cid %>
	    <% @tpur +=i.total_cost %>
	    <% @tsold += i.sold_total %>
	  <% end %>  
    <% end %>
  	<td><%= Company.find(@cid).name %>
    <td><%= @tpur %></td>
    <td><%= @tsold %></td>
    <% if @tsold>@tpur %>
      <td><%= @tsold-@tpur %></td>
    <% else %>
      <td><%= 0 %>
    <% end %>    
    <td><%= link_to 'Show', stocks_user_specific_stocks_path(c: @cid) %></td>
  </tr>
  <% end %>
</table>   

app/views/transactions/edit.html.erb
<h1>Edit transaction</h1>

<% @stsell = @transaction.stocks_bought %>
<%= form_for @transaction do |tran| %>
  <p>  
    Stocks Available: <%= tran.select :stocks_sold, options_for_select(1..@stsell), { prompt: "select" } %><br />
  </p>
  <%= tran.submit 'Sell Stock' %>
<% end %>   

app/views/transactions/index.html.erb
<h1>transaction index</h1>
 

<table>
	<tr>
		<th>User Name</th>
		<th>Company Name</th>
		<th>Stock Name</th>
		<th>Stocks Bought</th>
		<th>Stocks Sold</th>
	</tr>
	<% @transactions.each do |t| %>
	  <% if t.user_id==current_user.id %>
		  <tr>
		  	<td><%= @uname = User.find(t.user_id).name %>
		  	<td><%= @cname = Company.find(t.comp_id).name %></td>
		  	<td><%= @sname = Stock.find(t.stock_id).name %></td>
		  	<td><%= t.stocks_bought %>
		  	<td><%= t.stocks_sold_count %>	
		  	<td><%= link_to 'Show', transaction_path(t) %></td>
		  	  <td><%= link_to_if t.stocks_sold_count<t.stocks_bought, 'Sell', edit_transaction_path(t) %></td>
		  	<td><%= link_to 'Destroy', transaction_path(t), method: :delete, data: { confirm: 'Are you sure'} %></td>
		  </tr>
	   <% end %>	
	<% end %>  
</table>

<%= link_to 'Back', transactions_view_user_transaction_path %>
<%#= link_to 'Back', company_path(Stock.find_by_id(@transactions.stock_id).company) %>  

app/views/transactions/new.html.erb
<div class="container transaction-new">
  <h1>new transaction</h1>


  <%= form_for (@transaction) do |tran| %>
    <p>  
      Select Number Of Stocks: <%= tran.select :stocks_bought, options_for_select(1..@stav), { prompt: "select" } %><br />
    </p>
   
     <p>
      <%= tran.hidden_field :comp_id, readonly:true , value: @company_id %><br />
      <%= tran.hidden_field :stock_id, readonly:true , value: @stock_id %><br />
       <%= tran.hidden_field :user_id, readonly:true , value: @user_id %><br />

      </p>
    <% if @stav>0 %>  
      <%= tran.submit 'Buy Stock' %>
    <% else %>
      <p>Not Available</p>
    <% end %>    
    <%= link_to 'Back', company_path(Stock.find_by_id(@stock_id).company) %>

  <% end %>  
</div>  

app/views/transactions/sell_stock.html.erb
<h1>sell stock</h1>
<%= @transaction.id %>

<% @stsell = Transaction.find(@transaction.id).stocks_bought %>

<%= form_for @transaction, :url => stocks_add_to_stock_path(t_id: @transaction), :html => {:method => :post} do |tran| %>
  <p>  
    Stocks Available: <%= tran.select :stocks_sold, options_for_select(1..@stsell), { prompt: "select" } %><br />
  </p>
  <%= tran.submit 'Sell Stock' %>
<% end %>   

app/views/transactions/show.html.erb
<h1>transaction show</h1>

<h1><i>Details Of Stock Bought</i></h1>

<% @price = Stock.find(@transaction.stock_id).price %>
<p>User Name: <%= @user = User.find(@transaction.user_id).name %></p>
<p>Company Name: <%= @comp = Company.find(@transaction.comp_id).name %></p>
<p>Stock Name: <%= @st = Stock.find(@transaction.stock_id).name %></p>
<p>Stocks Bought: <%= @transaction.stocks_bought %></p>
<p>Total Cost: <%= @tcost = @transaction.stocks_bought*@price %></p>
<%#= @transaction.total_cost %>
<%#= @transaction.Purchasetotal %>

<%= link_to 'List All Stocks Bought', transactions_path(@transaction) %><br />
<%= link_to 'Home', welcome_index_path %> 

app/views/transactions/stockwise_total_transaction.html.erb
<h1>stockwise_total_transaction</h1>

<% @tcost = 0 %>
<% @stbought=0 %>
<% @tsold=0 %>
<% @stsoldcount=0 %>
<%# @test=0 %>

<% current_user.transactions.each do |i| %>
	<% if @st.id==i.stock_id %>
	  <%# @test += i.total_cost %>
	  <% @tcost = @tcost+(Stock.find(i.stock_id).price*i.stocks_bought) %>
	  <% @stbought += i.stocks_bought %>
	  <% @tsold += i.sold_total %>
	  <% @stsoldcount += i.stocks_sold %>
	<% end %>
<% end %>	

<div class="container">
	<div class="row">
		<div class="col-xs-12 col-sm-6">
			<div id="stocks_bought">
				<p>Stocks Bought: <%= @stbought %></p>
				<!-- <p>Price per unit: <%= @tcost/@stbought %></p> -->
				<p>-----------------------------</p>
				<p> Total Cost: <%= @tcost %>  </p>
			</div>
		</div>
        <div class="col-xs-12 col-sm-6">
        	<div id="stocks_sold">
				<p>Stocks Sold: <%= @stsoldcount %></p>
				<!-- <p>Price per unit: <%#= @tsold/@stsoldcount %></p> -->
				<p>-----------------------------</p>
				<p>Total Sold: <%= @tsold %></p>
			</div>
		</div>
	</div>
</div>
<!-- <p> Total Cost: <%#= @test %> </p> -->

app/views/transactions/total_purchase_sale.html.erb
<h1>total_purchase_sale</h1>

<% @tpur=0 %>
<% @tsold=0 %>
<% current_user.transactions.each do |i| %>
	<% @tpur +=i.total_cost %>
	<% @tsold += i.sold_total %>
<% end %>

<div class="container">
	<div>
		<div class="row">
			<div class="col-xs-12 col-sm-6">
	          <div id="total_purchase">
	          	<p>Total Purcase: <%= @tpur %></p>	
	          </div>
	        </div>
	        <div class="col-xs-12 col-sm-6">
	        	<div id="total_sold">
				  <p>Total Sold: <%= @tsold %>
				</div>
			</div>
		</div>
	</div>
	<div>
		<div class="row">
			<div class="col-xs-12">
				<div id="profit">
					<% if @tsold>@tpur %>
					  <p>Profit Amount: <%= @tsold-@tpur %></p>
					<% else %>
					  <p>Profit Amount: 0 </p>  
					<% end %>  
				</div>
			</div>
		</div>
	</div>
</div>

app/views/transactions/update_number_of_stock.html.erb
<h1>update_number_of_stock</h1>

<%= @transaction.stocks_bought %>
<%= @transaction.stocks_sold %>

app/views/transactions/view_user_transaction.html.erb
<div class="container">	
  <h1>view_user_transaction</h1>
  <div class="view-user-transaction">
	  <div class="row"> 
	    <div class="col-xs-12 col-sm-4">
	      <%= link_to 'List Transactions', transactions_path(@transaction) %><br />
	    </div>
	    <div class="col-xs-12 col-sm-4">  
	      <%= link_to 'View Companywise Details', transactions_companywise_stocks_bought_path %><br />
	    </div>
	    <div class="col-xs-12 col-sm-4">  
	      <%= link_to 'Total Purchase/Sale', transactions_total_purchase_sale_path %>
	    </div>  
	  </div>  
	  <%= link_to 'Back', welcome_index_path , class: 'btn btn-primary' %>
  </div> 	  
</div>  