config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do

      resources :users do
        resources :transactions
        resources :stocks
      end

      resources :companies do
        resources :stocks
      end
      
    end
  end

  get 'sessions/new'
 
  get 'welcome/index'

  resources :sessions

  get 'signup', to: 'users#new', as: 'signup'
get 'login', to: 'sessions#new', as: 'login'
get 'logout', to: 'sessions#destroy', as: 'logout'
get 'stocks/update_stocks_available'
get 'transactions/view_user_transaction'
get 'transactions/companywise_stocks_bought'
get 'transactions/stockwise_total_transaction'
get 'transactions/total_purchase_sale'
get 'transactions/sell_stock'
get 'transactions/update_number_of_stock'
get 'stocks/user_specific_stocks'


  resources :users do
    resources :transactions
    resources :stocks
  end

  resources :companies do
  	resources :stocks
  end

  resources :stocks
  resources :transactions

  #root 'welcome#index'
  root 'sessions#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if logged_in? %>
        <% @user = User.find(session[:user_id]) %>
        <%= link_to "#{@user.name}", welcome_index_path , class: "navbar-brand" %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if logged_in? %>
        <ul class="nav navbar-nav pull-right">
          <%= link_to 'Log out', logout_path , class: "btn navbar-btn" %>
        </ul>
        <ul class="nav navbar-nav pull-right">
          <%= link_to 'Home', welcome_index_path , class: "btn navbar-btn" %>
        </ul>
      <% else %>
        <ul class="nav navbar-nav pull-right">
          <%= link_to "Sign Up", signup_path , class: "btn navbar-btn" %>
        </ul>  
        <ul class="nav navbar-nav pull-right">
          <%= link_to "Log In", login_path , class: "btn navbar-btn" %>
        </ul>    
      <% end %>  
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>P1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application" %>

    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Tangerine|Inconsolata|Droid+Sans|Sofia|Alex+Brush|Amarante|Almendra+Display">
  </head>

  <body>
    <div id="flash_msg">
      <% flash.each do |key, value| %>
        <div >
          <% key %><%= value %>
        </div>
      <% end %>
    </div>  

    <%= render 'layouts/navbar' %>
    
    <% if logged_in? %>
      <% @user = User.find(session[:user_id]) %>           
    <% end %>


    <%= yield %>
  </body>
</html>